-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 19:54:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `id_number` INT(10) ZEROFILL NOT NULL,
  `passport` BIGINT NOT NULL,
  `experience` FLOAT NULL,
  `birth_date` DATE NOT NULL,
  `pharmacy_id` TINYINT NOT NULL,
  `post_id` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_number_UNIQUE` (`id_number` ASC) VISIBLE,
  UNIQUE INDEX `passport_UNIQUE` (`passport` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pharmacy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `building_number` VARCHAR(45) NOT NULL,
  `street_id` TINYINT NOT NULL,
  `web_address` VARCHAR(45) NOT NULL,
  `open_time` TIME NOT NULL,
  `close_time` TIME NOT NULL,
  `saturday` TINYINT NOT NULL,
  `sunday` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`street` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medecinelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medecinelist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ministry_code` VARCHAR(45) NOT NULL,
  `recipe` TINYINT NOT NULL,
  `narcotic` TINYINT NOT NULL,
  `psychotropic` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`effect_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`effect_zone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medecine_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medecine_zone` (
  `medecine_id` INT NOT NULL,
  `effect_zone_id` INT NOT NULL,
  PRIMARY KEY (`medecine_id`, `effect_zone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pharmacy_medecine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pharmacy_medecine` (
  `pharmacy_id` INT NOT NULL,
  `medecine_id` INT NOT NULL,
  PRIMARY KEY (`pharmacy_id`, `medecine_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
